### PR TITLE
Pull linkflowsalciafmt back to master

### PR DESCRIPTION
**Pull request by MoLi7**

### CODE REVIEW

**Comment by WesIngwersen** [comment]
@MoLi7 Let me know if tests of GHG model creation passed

**Review by WesIngwersen — COMMENTED** [review]
Approve pending confirmation that GHG models are identical to those from v0.1

**Comment by MoLi7** [comment]
@WesIngwersen 
Yes, I can confirm that GHG models are identical to those created by useeior v0.1. See this [function](https://github.com/WesIngwersen/SupplyChainGHGReport/commit/3c42b4507f39c3a9cf54e38a5fc711a0ce266525) for validation set up.

**Comment by WesIngwersen** [comment]
@bl-young @MoLi7 @jvendries @catherinebirney   FYI now pulling linktoflowsa into master

**Pull request merged**
