### PR TITLE
Handle import cost

### PR DESCRIPTION
**Pull request by MoLi7**
We are considering an alternative way to handle `import cost` due to issue raised in https://github.com/USEPA/useeior/issues/169.

The proposal is to remove `import cost` (a commodity-by-1 vector) from Domestic Use calculation, keep it as an independent model component `model$ImportCost` but not used in any model calculation, then in model constructing step append it as an additional column in Use (`model$U`) and Domestic Use (`model$U_d`).

Requesting help from @jvendries to add disaggregation/aggregation function to ensure `model$ImportCost` has the same amount of commodities with `model$U` and `model$U_d`, so that it can be directly appended to the tables.

### CODE REVIEW

**Comment by MoLi7** [comment]
`model$ImportCost` is renamed to `model$InternationalTradeAdjustment`. `model$InternationalTradeAdjustmentMeta` is added for convenient reference. It's ready for disaggregation @jvendries

**Comment by jvendries** [comment]
> `model$ImportCost` is renamed to `model$InternationalTradeAdjustment`. `model$InternationalTradeAdjustmentMeta` is added for convenient reference. It's ready for disaggregation @jvendries

Great, thanks for the update @MoLi7. One question for the disaggregation of this new model component is what allocation factors to use. The default option that I will begin working on is to use the gross output of the economic sectors as the allocation factors, but as we discussed this may not necessarily be accurate given that the trade volume/adjustments of the disaggregated sectors may not align with their overall economic output. Any suggestions on this are welcome.

**Comment by jvendries** [comment]
@MoLi7 Are these [lines](https://github.com/USEPA/useeior/blob/import_cost/R/LoadIOTables.R#L73-L76) supposed to refer to the new `model$InternationalTradeAdjusmentMeta` object? Currently they seem to be replacing the `model$InternationalTradeAdjusment` object rather than creating a new one. Please confirm.

**Comment by MoLi7** [comment]
> @MoLi7 Are these [lines](https://github.com/USEPA/useeior/blob/import_cost/R/LoadIOTables.R#L73-L76) supposed to refer to the new `model$InternationalTradeAdjusmentMeta` object? Currently they seem to be replacing the `model$InternationalTradeAdjusment` object rather than creating a new one. Please confirm.

It should be `model$InternationalTradeAdjustmentMeta`, fixed in 9d116d7ae0fb1f1ea390c99d49e34e2b0146636b. Thanks!

**Comment by jvendries** [comment]
@MoLi7 I added a function to disaggregate the `model$InternationalTradeAdjustment` object and ran the model build to completion without any errors (no modifications were needed in the aggregation functions). Please check that the code runs for you with the most recent commit and that the resulting model object conforms to your expectations.

I did not disaggregate the `model$InternationalTradeAdjustementMeta` object as this object does not contain references to the sectors we want to disaggregate (similar to the `FinalDemandMeta `and `ValueAddedMeta `objects). 

Please let me know if there is anything I missed for the disaggregation of these objects. 

Thanks!

**Comment by MoLi7** [comment]
This modification about international trade adjustment is ready to be merged into `develop`. This will lead to additional discussion about [preparing Import demand vector](https://github.com/USEPA/useeior/pull/172/commits/1868a097ade1da1b88d2671ad96c97b87f3ef48b) - I will initiate it in https://github.com/USEPA/useeior/pull/172.

**Comment by MoLi7** [comment]
@WesIngwersen all changes are made per our discussion. Please review.

**Comment by MoLi7** [comment]
This one should be ready to merge, too. @WesIngwersen

**Pull request merged**
