### PR TITLE
Identify and update remaining commodity names to make v2.0 compatible…

### PR DESCRIPTION
**Pull request by WesIngwersen**
… with v1.2

### CODE REVIEW

**Comment by WesIngwersen** [comment]
All changes of BEA 2012 code commodity names are by taking the 2007 sector commodity name when the sector deifnitions have a 1-to-1 match in the [2007-to-2012 mapping](https://github.com/USEPA/useeior/blob/master/inst/extdata/Crosswalk_DetailIndustry2007and2012Schemas.csv).

There are a couple exceptions. 
4A0000  Other retail (2007), includes more retail than the 4B0000 (2012) because in 2012 more retails sectors are broken out from the original 4A00000, but still the definitions of Other retail are equivalent.

and there are a couple cases where i just provided names that were in commodity-style for 2012 where they still sounded like industry names

**Comment by MoLi7** [comment]
I have a question about 331313 (v2.0) vs 33131A (v1.2), they are matched in the [2007-to-2012 mapping](https://github.com/USEPA/useeior/blob/master/inst/extdata/Crosswalk_DetailIndustry2007and2012Schemas.csv), but one is "Primary aluminum" while the other is "Aluminum", should we stick with the latter?

Name | 2.0 code | 1.2 code
Primary aluminum | 331313 | NA
Aluminum | NA | 33131A

**Comment by MoLi7** [comment]
Here is another example: 332996 is a valid code in v2.0 and v1.2, but it has different names.

Name | 2.0 code | 1.2 code
Fabricated pipe and pipe fittings | NA | 332996
Metal pipe and pipe fittings | 332996 | NA

**Comment by MoLi7** [comment]
Another one... 332999==33299B, but names are different.

Name | 2.0 code | 1.2 code
Metal pipe fittings, ball and roller bearings, industrial patterns, metal bath fixtures, other misc. fabricated metals | NA | 33299B
Misc. fabricated metal products | 332999 | NA

**Comment by MoLi7** [comment]
Another one for 333313 and 333318, they should have the same name.

Name | 2.0 code | 1.2 code
Office machinery | NA | 333313
Other commercial and service industry machinery | 333318 | NA

**Comment by MoLi7** [comment]
> There are a couple exceptions.
> 4A0000 Other retail (2007), includes more retail than the 4B0000 (2012) because in 2012 more retails sectors are broken out from the original 4A00000, but still the definitions of Other retail are equivalent.

@WesIngwersen I suppose the exceptions should also include cases like 33331A and 333313 (2007) matches 333318 (2012), they each could have different names.

**Comment by WesIngwersen** [comment]
> Name | 2.0 code | 1.2 code
> Primary aluminum | 331313 | NA
> Aluminum | NA | 33131A

We need to distinguish between Primary and Secondary Aluminum, which is what I used that after re-reading NAICS. 
I think the mapping file needs to be updated to also map to the Secondary Aluminum, 331314

**Comment by WesIngwersen** [comment]
> Here is another example: 332996 is a valid code in v2.0 and v1.2, but it has different names.
> 
> Name | 2.0 code | 1.2 code
> Fabricated pipe and pipe fittings | NA | 332996
> Metal pipe and pipe fittings | 332996 | NA

I agree that this one could change...i think i did that but you are correct that is should have the same name

**Comment by WesIngwersen** [comment]
> Another one... 332999==33299B, but names are different.
> 
> Name | 2.0 code | 1.2 code
> Metal pipe fittings, ball and roller bearings, industrial patterns, metal bath fixtures, other misc. fabricated metals | NA | 33299B
> Misc. fabricated metal products | 332999 | NA

I reviewed that one. [332999](https://www.census.gov/naics/?input=332999&year=2012&details=332999) does not include pipe fittings or ball bearings

**Comment by WesIngwersen** [comment]
> Another one for 333313 and 333318, they should have the same name.
> 
> Name | 2.0 code | 1.2 code
> Office machinery | NA | 333313
> Other commercial and service industry machinery | 333318 | NA

[333318](https://www.census.gov/naics/?input=333318&year=2012&details=333318) is now broader than Office Machinery (33313 from NAICS 2007). See the mapping file at the bottom of that page.

**Comment by MoLi7** [comment]
> > Name | 2.0 code | 1.2 code
> > Primary aluminum | 331313 | NA
> > Aluminum | NA | 33131A
> 
> We need to distinguish between Primary and Secondary Aluminum, which is what I used that after re-reading NAICS.
> I think the mapping file needs to be updated to also map to the Secondary Aluminum, 331314

I reviewed 2007 and 2012 Use tables, 33131A (2007) exclusively corresponds to 331313 (2012), and they have the same name of "Alumina refining and primary aluminum production", so no change needed in the mapping, plus 33131A should be "Primary aluminum", too.

**Comment by MoLi7** [comment]
> > Here is another example: 332996 is a valid code in v2.0 and v1.2, but it has different names.
> > Name | 2.0 code | 1.2 code
> > Fabricated pipe and pipe fittings | NA | 332996
> > Metal pipe and pipe fittings | 332996 | NA
> 
> I agree that this one could change...i think i did that but you are correct that is should have the same name

Okay I will change it to "Fabricated pipe and pipe fittings". It's odd that "Metal pipe and pipe fittings" did not exist in v1.2SectorNames or 2007 Use table.

**Comment by WesIngwersen** [comment]
> > > Name | 2.0 code | 1.2 code
> > > Primary aluminum | 331313 | NA
> > > Aluminum | NA | 33131A
> > 
> > 
> > We need to distinguish between Primary and Secondary Aluminum, which is what I used that after re-reading NAICS.
> > I think the mapping file needs to be updated to also map to the Secondary Aluminum, 331314
> 
> I reviewed 2007 and 2012 Use tables, 33131A (2007) exclusively corresponds to 331313 (2012), and they have the same name of "Alumina refining and primary aluminum production", so no change needed in the mapping, plus 33131A should be "Primary aluminum", too.
> 
> New note:
> 
> 1. 331314 is an industry but not a commodity, so it should removed from this commodity name table.
> 2. "331313 Primary aluminum" and "33131B Secondary aluminum" in 2012 was "33131A Aluminum" and "33131B Aluminum products" in 2007, which set of names should we maintain? @WesIngwersen

Thanks for raising.  I remember now that about the aluminum only having the one commodity....this explains the pure use of "Aluminum" from the previous model since both primary Al nd secondary Al industries are producing it.  So this is a special case.  I'm not sure though about the `Aluminum products` name.

**Comment by WesIngwersen** [comment]
Take a look at BEA mapping to NAICS for that one as well as the NAICS definitions and please make a recommendation, thanks

**Comment by MoLi7** [comment]
> Thanks for raising. I remember now that about the aluminum only having the one commodity....this explains the pure use of "Aluminum" from the previous model since both primary Al nd secondary Al industries are producing it. So this is a special case. I'm not sure though about the `Aluminum products` name.

Yes, the footnote in the "NAICS Code" sheet in BEA Use table has explicit description for it.

> Take a look at BEA mapping to NAICS for that one as well as the NAICS definitions and please make a recommendation, thanks

Based on the BEA's footnote and NAICS definitions of the related industries, I'd recommend using "Primary aluminum" and "Secondary aluminum" for both v2.0 and v1.2.

**Pull request merged**
