### PR TITLE
Refac mastercrosswalk

### PR DESCRIPTION
**Pull request by MoLi7**
@catherinebirney I made some changes to slightly simplify the approach of generating MasterCrosswalk. Please review the commits and let me know if you have any questions. Thanks!

### CODE REVIEW

**Review by WesIngwersen — COMMENTED** [review]
Do you think this could effect the satellite table amounts in v2.0 just through its use in LoadSatellites.R?

**Comment by MoLi7** [comment]
> Do you think this could effect the satellite table amounts in v2.0 just through its use in LoadSatellites.R?

@WesIngwersen it could affect FlowAmount on housing and maybe government as well. All the other sectors should not be affected.

**Comment by catherinebirney** [comment]
@MoLi7 The mastercrosswalk row for BEA_2012_Detail_Code = S00201 shows that NAICS_2012_Code = NA, when NAICS_2012 should be S00201. This assignment gets pulled in from G_BEAtoUSEEIOtoNAICS_2012.csv. I'm not sure why/how the NAICS assignment gets dropped

**Comment by MoLi7** [comment]
> @MoLi7 The mastercrosswalk row for BEA_2012_Detail_Code = S00201 shows that NAICS_2012_Code = NA, when NAICS_2012 should be S00201. This assignment gets pulled in from G_BEAtoUSEEIOtoNAICS_2012.csv. I'm not sure why/how the NAICS assignment gets dropped

@catherinebirney did you `devtools::load_all()` after pulling the branch? If not, you probably are seeing the previous version of MasterCrosswalk2012.

I ran this code and could see NAICS_2012 is S00201
`useeior::MasterCrosswalk2012[useeior::MasterCrosswalk2012[, "BEA_2012_Detail_Code"]=="S00201",]
      BEA_2012_Sector_Code BEA_2012_Summary_Code BEA_2012_Detail_Code NAICS_2012_Code NAICS_2007_Code NAICS_2017_Code
16623                    G                  GSLE               S00201          S00201            <NA>            <NA>`

**Review by catherinebirney — APPROVED** [review]
@MoLi7 i had not run devtools::load_all() - that fixed it! Changes look good to me

**Comment by MoLi7** [comment]
@WesIngwersen shall I merge this PR or you'd like to inspect the changes it causes in LoadSatellites.R? Let me know if you'd like my inputs. Thanks!

**Comment by WesIngwersen** [comment]
I will go ahead and merge, thanks

**Pull request merged**
