### PR TITLE
Release v1.6.0

### PR DESCRIPTION
**Pull request by bl-young**
- Includes new features to support the incorporation of Import Emission Factors (IEFs) for single and two-region models, results in new matrices $M_m$ and $N_m$ for coefficients of imported goods.
- Detail (`USEEIOv2.3-GHG`) and summary model (`USEEIOv2.3-s-GHG-19`) based on 2019 GHG data are added with IEFs from EXIOBASE.
- Household/final user emissions are added via $B_h$ matrix

### CODE REVIEW

**Comment by WesIngwersen** [comment]
Do you understand the nature of this permissions error coming up in the github actions?

**Comment by WesIngwersen** [comment]
@andychase @cgriff02   We're getting a new error running our actions related to a package not present in an approved list? Any insight?

**Comment by bl-young** [comment]
It's brand new today, wasn't present yesterday.

**Comment by andychase** [comment]
Weird, well I added quarto-dev/* and re-ran the action
________________________________

**Comment by WesIngwersen** [comment]
Closing this as release v1.6.0 was made from the v1.6.0 branch. All permanent changes are in develop. Only the temporary commenting out of some external functions was done in this branch.  Will remove the branch.

**Pull request closed without merging**
