### PR TITLE
Add more model demand vectors & refactor validation function for industry models

### PR DESCRIPTION
**Pull request by MoLi7**
One existing model demand vector is modified (838136c135213f2d1cb6343e14302d55e7ec16bb). Two new demand vectors are added (0e6ab39dcc54ae7121fe7e0c12a6cb47fe60c09b and 1868a097ade1da1b88d2671ad96c97b87f3ef48b) to make validation function compatible with industry models

Validation functions `compareEandLCIResult` and `compareOutputandLeontiefXDemand` are refactored to work for industry model:
```
> modelname <- 'USEEIOv2.0is-GHG_nodisagg'
> model <- buildModel(modelname, configpaths = NULL)
> val_1 <- compareEandLCIResult(model, use_domestic = FALSE, tolerance = 0.05)
> val_1$N_Failure
[1] 0
> val_1_domestic <- compareEandLCIResult(model, use_domestic = TRUE, tolerance = 0.05)
> val_1$N_Failure
[1] 0
> val_2 <- compareOutputandLeontiefXDemand(model, use_domestic = FALSE, tolerance = 0.05)
> val_1$N_Failure
[1] 0
> val_2_domestic <- compareOutputandLeontiefXDemand(model, use_domestic = TRUE, tolerance = 0.05)
> val_1$N_Failure
[1] 0
```

### CODE REVIEW

**Comment by WesIngwersen** [comment]
Looks great

**Comment by MoLi7** [comment]
@WesIngwersen thanks! If you approve it, I will complete the merge.

**Comment by MoLi7** [comment]
@WesIngwersen demand vector year should == model IO year, right? If so, I will create a anchor for model IO year and let demand vector year use that anchor to avoid hard code.

https://github.com/USEPA/useeior/blob/51ab301db0076f2e95de1b8ca289bba5dabb29d1/inst/extdata/modelspecs/USEEIOv2.0is-GHG_nodisagg.yml#L60

https://github.com/USEPA/useeior/blob/51ab301db0076f2e95de1b8ca289bba5dabb29d1/inst/extdata/modelspecs/USEEIOv2.0is-GHG_nodisagg.yml#L4

**Comment by WesIngwersen** [comment]
I think we should leave the demand year flexible. It would be possible to use demands that represent other years with a model. We just have not done that yet.

**Comment by MoLi7** [comment]
> I think we should leave the demand year flexible. It would be possible to use demands that represent other years with a model. We just have not done that yet.

That's a fair point. What about supply chain GHG models? `USEEIOv2.0.10-GHG` should have demand year of 2010, while `USEEIOv2.0.16-GHG` should have demand year of 2016, right? @WesIngwersen

**Pull request merged**
