### PR TITLE
Update form of model$Industries and model$Commodities

### PR DESCRIPTION
**Pull request by MoLi7**
I updated the form in several places in the code, but the changes are only limited to `model$Industries` and `model$Commodities`. Row and column names in all IO tables are not changed yet as I'm waiting for @WesIngwersen 's response to [my comment](https://epalca.atlassian.net/browse/USEEIO-984?focusedCommentId=13026).

@jvendries please update the form in disaggregation for `model$Industries` and `model$Commodities`, thanks!

### CODE REVIEW

**Comment by MoLi7** [comment]
@WesIngwersen I implemented the new form `sector/location`, e.g. `1111A0/US`, throughout all IO tables and demand vectors. All details look good in USEEIOv2.0_nodisagg model results, e.g. model$B, model$M, model$U, etc.

Now waiting on updates from @jvendries to complete this PR.

**Comment by WesIngwersen** [comment]
@jvendries can you give us an update?

**Comment by jvendries** [comment]
@WesIngwersen @MoLi7 
I apologize, I was under the impression that this would be merged first and then I'd update the disaggregation input files to reflect the new format since I was can't test the with the new format before this is merged. I can update the input files to reflect the new form before this is merged, but in that case it would be helpful if you could test the disaggregation input files before merging to make sure everything is working properly.

**Comment by jvendries** [comment]
@MoLi7 I'm working on updating the disaggregation functions to include the new format for the sector codes, but I ran into an error in the code execution that seems to be caused by the model$MultiYearIndustryOutput, model$MultiYearIndustryCPI, and model$MultiYearCommodityCPI objects. These objects don't seem to have the updated format for the sector codes (i.e. they still lack the geographic component). I pulled again the most recent changes to my machine to make sure I wasn't missing any commits and I don't think I am. Can you please check that these objects have the updated sector code format?

**Comment by MoLi7** [comment]
@jvendries right, the model$MultiYear dfs did not have the new form, but now they should - please pull to see the latest commit.

**Comment by jvendries** [comment]
@MoLi7 I've updated the disaggregation input files to the new format, and tested the code to make sure it runs to completion with the new format for the disaggregated model. I also updated the model$SectorNames object to include the primary region acronym as it had not been updated to include it. Please take a look at this change to make sure it does not adversely affect non-disaggregation functions.

**Comment by MoLi7** [comment]
Thanks @jvendries for the updates! I was on the fence about whether to include the primary region in model$SectorNames, but now I think it should be there. This means there are many more modifications needed in the code for processing TbS and CbS. @WesIngwersen let me know if have a different opinion.

P.S. @jvendries could you modify [this line of code](https://github.com/USEPA/useeior/blob/e97c96f8af083117425980b4294de58fdecd055a/R/DisaggregateFunctions.R#L780) to avoid converting the disaggregated column from `character` to `factor`? Having column(s) in `factor` format can be problematic downstream...

**Comment by jvendries** [comment]
> P.S. @jvendries could you modify [this line of code](https://github.com/USEPA/useeior/blob/e97c96f8af083117425980b4294de58fdecd055a/R/DisaggregateFunctions.R#L780) to avoid converting the disaggregated column from `character` to `factor`? Having column(s) in `factor` format can be problematic downstream...

Pushed a commit that should remove the conversion from character to factor.

**Comment by WesIngwersen** [comment]
> The Sector column in satellite table will include '/US' which is duplicated info of the Location column, @WesIngwersen would you think it is redundant?

Yes I think here it is redundant to have both so should leave Sector just with the code in this format, because it has the Location split out in a separate fields. Also this is a flowsa-defined format, so it would be inconsistent with that if we change it here

**Comment by WesIngwersen** [comment]
I just resolved the conflict - i had moved the getMarginTable to the Margins.R file so it doesn't need to be in IOfunctions.

**Comment by WesIngwersen** [comment]
Just tested model build and B and C and all result matrices are not building properly yet, I assume due to this issue @MoLi7 raised about the Sector column in the satellite table. Let's leave this PR open until that is resolved.

**Comment by jvendries** [comment]
> > The Sector column in satellite table will include '/US' which is duplicated info of the Location column, @WesIngwersen would you think it is redundant?
> 
> Yes I think here it is redundant to have both so please leave Sector just with the code in this format, because it has the Location is present in a separate field. Also this is a flowsa-defined format, so it would be inconsistent with that if we change it here.

@MoLi7 Since we want to leave `model$Sector` without the geography component, should I revert the change to LoadFunctions.R I committed so that I can work on adapting the disaggregation of this object without including the geography component?

**Comment by MoLi7** [comment]
> @MoLi7 Since we want to leave `model$Sector` without the geography component, should I revert the change to LoadFunctions.R I committed so that I can work on adapting the disaggregation of this object without including the geography component?

@jvendries I think we still want to have location in `model$SectorNames` so that it is consistent with all other model components. To avoid the redundancy in sat tables, I think we can keep `model$SectorNames` location-less for mapping flowsa to useeior. Once `model$SatelliteTables$totals_by_sector` are generated, we can add location in `model$SectorNames` perhaps in the very last step of model building, i.e. `buildEEIOModel()`.

@WesIngwersen please share your thoughts on this so that @jvendries can decide whether to revert his change.

**Comment by WesIngwersen** [comment]
Yes I agree with that

**Comment by jvendries** [comment]
If we want to add location to `model$SectorNames` in `buildEEIOModel()`, it will require reverting the change I did and disaggregating  `model$SectorNames` without the location component, so I'll go ahead and do that. @MoLi7 can you please add the location component back in in `buildEEIOModel()`?

**Comment by MoLi7** [comment]
@jvendries yes, I will do that. I will also update `loadIOData` to not add location there. Thanks for coordinating on this!

**Comment by MoLi7** [comment]
@jvendries please pull to see changes from my side.

**Comment by jvendries** [comment]
@MoLi7 @WesIngwersen `model$SectorNames` should be disaggregated without the location identifier in the most recent push.

**Comment by WesIngwersen** [comment]
@MoLi7 Can we pull this in now?

**Comment by WesIngwersen** [comment]
USEEIOv2.0_nodisagg model builds correctly and validates.  There are a few more flows that were not present in my previously saved version of this model, but i don't think it is these refac_IO updates affecting that.

**Comment by bl-young** [comment]
@WesIngwersen  The new parquets from flowsa include Catherine's fix to the out-dated NAICS sectors, which in prior parquets was causing a handful of flows to drop, so yes there should be a few new flows in the model now.

**Comment by jvendries** [comment]
I tested USEEIOv2.0 to make sure it builds without errors. I am still adjusting (in a separate branch) the disaggregation allocations to avoid the colSums(model$V_n) issue, so it the disaggregated model might not validate correctly but that should not prevent this branch from being merged.

**Pull request merged**
