### PR TITLE
V2 alpha merge

### PR DESCRIPTION
**Pull request by WesIngwersen**

### CODE REVIEW

**Comment by WesIngwersen** [comment]
My biggest concern now is the inability to read in the BEA data due to BEA's recent major change.  My proposal is to save the main BEA files (like the AllBEAIO.zip) to the Data Commons to be able to read them with the code and build from there - that way we'd just have to change the URL for now.

**Comment by catherinebirney** [comment]
> My biggest concern now is the inability to read in the BEA data due to BEA's recent major change. My proposal is to save the main BEA files (like the AllBEAIO.zip) to the Data Commons to be able to read them with the code and build from there - that way we'd just have to change the URL for now. We could do that before pulling this into master.

I uploaded the two zip files in dropbox to Data Commons.
[AllTablesIO.zip link](https://edap-ord-data-commons.s3.amazonaws.com/useeior/AllTablesIO.zip)
[AllTablesUnderlying.zip link](https://edap-ord-data-commons.s3.amazonaws.com/useeior/AllTablesUnderlying.zip)

Let me know if there are any additional files to upload

**Comment by MoLi7** [comment]
> I uploaded the two zip files in dropbox to Data Commons.
> [AllTablesIO.zip link](https://edap-ord-data-commons.s3.amazonaws.com/useeior/AllTablesIO.zip)
> [AllTablesUnderlying.zip link](https://edap-ord-data-commons.s3.amazonaws.com/useeior/AllTablesUnderlying.zip)
> 
> Let me know if there are any additional files to upload

It's just these two, URLs of all the other files are working fine now, thanks @catherinebirney !

**Comment by MoLi7** [comment]
@WesIngwersen the invalid BEA urls have been replaced.

I noticed the [example](https://github.com/USEPA/useeior/tree/v2-alpha/examples) scripts are not updated yet, shall we modify them before merging?

**Comment by WesIngwersen** [comment]
Yes sure update examples and merge, thanks.

**Review by MoLi7 — APPROVED** [review]

**Pull request merged**
