### PR TITLE
Bio-modeling in fork into Bioeconomy in main

### PR DESCRIPTION
**Pull request by WesIngwersen**
@cga203, the first step should be to merge this into our Bioeconomy branch in the main useeior and work on it from there.  This way we will bring your most recent updates in. We will have to work out some merge conflicts.

### CODE REVIEW

**Comment by WesIngwersen** [comment]
The Bioeconomy branch is now updated to the latest master branch code

**Comment by cga203** [comment]
@WesIngwersen These 6 commits are not the latest ones I've made on the Bio-modeling branch I have been working on. I have done three more in the last week. On my Github desktop it says the commits have not been pushed to the remote repository. I don't remember how to push them.

**Comment by cga203** [comment]
@WesIngwersen  Those 6 commits aren't my most recent ones. I just noticed I have committed, but not pushed the new ones. I just did that.

**Comment by WesIngwersen** [comment]
> @WesIngwersen Those 6 commits aren't my most recent ones. I just noticed I have committed, but not pushed the new ones. I just did that.

No problem - those 6 commits are now part of this PR as you can see under the commits tab. Thanks for pushing those.

**Pull request merged**
