### PR TITLE
Refactor margins

### PR DESCRIPTION
**Pull request by MoLi7**
This PR will pull refactoring of margins into v2-alpha.

### CODE REVIEW

**Comment by WesIngwersen** [comment]
`model$FinalDemandSectors$Code_Loc` is incorrect and a possible cause as well of issue #115 
for USEEIOv2.0 it is 
```
 [1] "1/US"  "2/US"  "3/US"  "4/US"  "5/US"  "6/US"  "7/US"  "8/US"  "9/US"  "10/US" "11/US" "12/US" "13/US" "14/US"
[15] "15/US" "16/US" "17/US" "18/US" "19/US" "20/US"
```
looks like the `Code` and `Name' fields are factors which could be breaking a concatenation function

`model$MarginSectors` has the same issue

**Comment by WesIngwersen** [comment]
On a related now, the method for building model$FinalDemandSectors is not suitable 
```
model$FinalDemandSectors <- cbind.data.frame(BEA$FinalDemandCodes,
                                               c("Household", rep("Investment", 4), "ChangeInventories", "Export", "Import", rep("Government", 12)))
  
```
This setup appears to be based just on the BEA Detail Schema

**Comment by WesIngwersen** [comment]
interesting notes on model$PriceTypeRatio.  
It's negative for scrap. I do think this might be an issue
it's slightly > 1 for Other state and local gov enterprises. Not sure how to handle that but i think conceptually its OK.

**Comment by WesIngwersen** [comment]
I assigned the new price ratio matrices names consistent with our nomenclature -  rho was used as a price year adjustment vector in Appendix 1 of the Supply Chain GHG Factor report; phi was used as the price type adjustment vector. This trend to use Greek letters for ratio matrices was continued with my choice of Chi for the output ratio matrices we used in the validation.

**Comment by WesIngwersen** [comment]
FYI with recent updates the size on disk of the v2.0 model as RData is about 40% smaller than it was before the more recent refactoring that dropped BEA and GDP objects, even with the additionals of price matrices

**Review by WesIngwersen — APPROVED** [review]

**Comment by MoLi7** [comment]
Thanks for the in-depth review @WesIngwersen ! I pushed a few commits and tested model build step-by-step to assure model objects, particularly the final demand and margin sectors, are correct at all levels of detail (I tried USEEIOv2.0, USEEIOv2.0s-GHG, and USEEIOv2.0c-GHG). They should also fix the error in loadDemandVectors you encountered earlier.

**Comment by MoLi7** [comment]
> interesting notes on model$PriceTypeRatio.
> It's negative for scrap. I do think this might be an issue
> it's slightly > 1 for Other state and local gov enterprises. Not sure how to handle that but i think conceptually its OK.

Right, I think the slightly > 1 and < 0 values are conceptually reasonable, too. @WesIngwersen

**Pull request merged**
