### PR TITLE
Update validation with more features

### PR DESCRIPTION
**Pull request by MoLi7**
This PR is opened for discussion about adding more features to validation.

### CODE REVIEW

**Comment by MoLi7** [comment]
@WesIngwersen https://github.com/USEPA/useeior/pull/102/commits/03989f8544fc8f554023451606731da6fc18b3fd proposes a solution for this Jira [task](https://epalca.atlassian.net/browse/USEEIO-1030), please execute `compareEandLCIResult` to see the updated validation result, and give feedbacks, thanks!

**Comment by WesIngwersen** [comment]
I removed one bad line from compareOutputandLeontief() but now that and compareEandLCIResult are giving me this error

```
 Error in names(object) <- nm : 
  'names' attribute [1] must be the same length as the vector [0] 
5.
setNames(data.frame(data), value.name) 
4.
melt.default(confrontation, id.vars = c("rownames", "name", "expression")) 
3.
reshape2::melt(confrontation, id.vars = c("rownames", "name", 
    "expression")) at ValidateModel.R#217
2.
extractValidationResult(comparison$confrontation, failure = FALSE) at ValidateModel.R#55
1.
compareEandLCIResult(model, output_type = "Industry") 
```

**Comment by MoLi7** [comment]
> I removed one bad line from compareOutputandLeontief() but now that and compareEandLCIResult are giving me this error
> 
> ```
>  Error in names(object) <- nm : 
>   'names' attribute [1] must be the same length as the vector [0] 
> 5.
> setNames(data.frame(data), value.name) 
> 4.
> melt.default(confrontation, id.vars = c("rownames", "name", "expression")) 
> 3.
> reshape2::melt(confrontation, id.vars = c("rownames", "name", 
>     "expression")) at ValidateModel.R#217
> 2.
> extractValidationResult(comparison$confrontation, failure = FALSE) at ValidateModel.R#55
> 1.
> compareEandLCIResult(model, output_type = "Industry") 
> ```

I believe this is because several `validate` functions are wrapped, so may be somehow masked, in our customized functions. I think it's `confrontation <- validate::as.data.frame(confrontation)` that causes such error, because what I experienced before was if I ran `validate::as.data.frame` outside of any wrapper first, then it wouldn't throw any error when executed in a wrapper.

Unfortunately, I have not found a solution to this, but I will keep look for one.

**Comment by MoLi7** [comment]
@WesIngwersen I abandoned `validate::as.data.frame` instead of the package entirely, because the package itself is quite handy.

In ba07ae2a251384d768271dbb1f24a1d66e239f47, I dug into the `confrontation` object and extracted the `TRUE/FALSE` part directly, which returned what we want.

Although I still don't know why `validate::as.data.frame` malfunctions on `confrontation` object when wrapped in a customized function, I'm suspecting it must have some sort of bug [here](https://github.com/data-cleaning/validate/blob/2b9972ec6e22350db256997670fad66db48170c0/pkg/R/confrontation.R#L826) that makes it falsely detect error or warning in the object. I plan to open an issue in their GitHub repo and describe the problem with a simplified example, hopefully I can have a better understanding of what is going on in `validate::as.data.frame`.

**Comment by WesIngwersen** [comment]
I'm getting an error with the new formatting function - its not finding all the right names in that comparison$confrontation object 

```
7. stop("id variables not found in data: ", vars, call. = FALSE) 
6. melt_check(data, id.vars, measure.vars, variable.name, value.name) 
5. melt.data.frame(confrontation, id.vars = c("rownames", "name",  "expression")) 
4. reshape2::melt(confrontation, id.vars = c("rownames", "name",  "expression")) at ValidateModel.R#200
3.  extractValidationResult(comparison$confrontation, failure = FALSE) at ValidateModel.R#219
2. formatValidationResult(as.data.frame(rel_diff), tolerance) at ValidateModel.R#53
1. compareEandLCIResult(model, output_type = "Industry") 

```
FYI I have v.1.0.1 of validate installed

**Comment by WesIngwersen** [comment]
One more minor change I would request is to actually return a list that contains that validation list that you created and are currently returning, but the two calculated objects being returned as well....  like E and LCI.  That way we have that raw data available if we want to inspect it more closely

**Comment by WesIngwersen** [comment]
Note my most recent commit was https://epalca.atlassian.net/browse/USEEIO-1018
I went ahead and did that now in this branch. Shouldn't affect this issue.

**Comment by MoLi7** [comment]
> I'm getting an error with the new formatting function - its not finding all the right names in that comparison$confrontation object
> 
> ```
> 7. stop("id variables not found in data: ", vars, call. = FALSE) 
> 6. melt_check(data, id.vars, measure.vars, variable.name, value.name) 
> 5. melt.data.frame(confrontation, id.vars = c("rownames", "name",  "expression")) 
> 4. reshape2::melt(confrontation, id.vars = c("rownames", "name",  "expression")) at ValidateModel.R#200
> 3.  extractValidationResult(comparison$confrontation, failure = FALSE) at ValidateModel.R#219
> 2. formatValidationResult(as.data.frame(rel_diff), tolerance) at ValidateModel.R#53
> 1. compareEandLCIResult(model, output_type = "Industry") 
> ```
> 
> FYI I have v.1.0.1 of validate installed

@WesIngwersen this should be caused by the `validate` package - it still does not work as we expected and is much more complicated than I thought. I'm clueless about why it cannot take parameters of wrapper function... I'm thinking about abandoning it and use some basic comparing method instead.

**Comment by MoLi7** [comment]
@WesIngwersen 0a3f4f5690bc59264c608f4eaaf61651d3b6d08f simplifies the validation approach, e.g. generating `TRUE/FALSE`, using the basic `rel_diff <= tolerance` method. It should work now.

**Pull request merged**
