### PR TITLE
Write sector metadata to support json export

### PR DESCRIPTION
**Pull request by bl-young**
- Update metadata files to include sector categories and descriptions. (note new field 'Category' will be needed for API)
- add these fields to disaggregated input files 
- Ensure UUIDs are correctly maintained in satellite tables and exported.
- Add model spec 2.0.1 for updated satellite tables w UUIDs (not yet completed for FBS via flowsa)

Confirmed that v2.0 still functions and exports without UUIDs

### CODE REVIEW

**Comment by bl-young** [comment]
@MoLi7 @WesIngwersen sorry I forgot I still need to update the categories to align with FLCAC, otherwise though this is ready for review.

**Review by MoLi7 — APPROVED** [review]
@bl-young I can see there are 71 unique FlowUUIDs in`USEEIO2.0.1$TbS`, I suppose there will be more coming in to replace `""` in the FlowUUID column as FBS in flowsa gets updated?

**Comment by bl-young** [comment]
> @bl-young I can see there are 71 unique FlowUUIDs in`USEEIO2.0.1$TbS`, I suppose there will be more coming in to replace `""` in the FlowUUID column as FBS in flowsa gets updated?

correct, only the csv files on data commons have been updated with UUIDs, the other satellite tables should be ready soon which will fill in the others. The waste flows may be blank a bit longer.

**Comment by bl-young** [comment]
@WesIngwersen do you plan to review this?

**Review by WesIngwersen — APPROVED** [review]

**Pull request merged**
