### PR TITLE
Update Summary commodity names in USEEIO_Commodity_Meta.csv.

### PR DESCRIPTION
**Pull request by MoLi7**
This is a hotfix (branched off from `master`) to resolve issue #208.

### CODE REVIEW

**Comment by MoLi7** [comment]
I wonder how you created the `Category`, `Subcategory` and `Description` columns for Detail commodity in USEEIO_Commodity_Meta.csv? @bl-young 
Can we fill out those columns for Summary commodity (ln 432-502) in a non-manual way?

**Comment by bl-young** [comment]
`Category` and `Subcategory` align with the Federal Commons Category structure. So I would expect all summary level commodities should be added to an existing folder in the file. 
`Description` was populated for most commodities back in v1.1 for use in openLCA. We only updated commodities that are new in v2.0.
All of which is to say, they were all done manually. 
`Category` and `Subcategory` should be quite quick to add. `Description` would take more time. Though all 3 of these fields are really only relevant for use in openLCA.

**Comment by bl-young** [comment]
@MoLi7 I can add category and subcategory real quick on this PR

**Comment by MoLi7** [comment]
> @MoLi7 I can add category and subcategory real quick on this PR

That'd be great! Thanks!!

**Comment by bl-young** [comment]
Subcategories tend to be 4-digit NAICS and so do not apply for summary model schema

**Comment by bl-young** [comment]
@MoLi7 does this need to be pulled in?

**Pull request merged**
