### PR TITLE
Add documentation of disaggregation functions and config files

### PR DESCRIPTION
**Pull request by WesIngwersen**
We have to pull this into v2-alpha to solve this documentation build issue that is not allowing us to gen docs in v2-alpha or branches from that origin

### CODE REVIEW

**Comment by WesIngwersen** [comment]
> o keep all .Rd files up-to-date, I'd suggest hitting Shift+Ctrl+D every time you are done updating/adding new functions/data in RStudio.

@MoLi7  next time see if you can get the authors of the docs to do this so they get the commit credits.

**Comment by WesIngwersen** [comment]
@MoLi7  Did you miss adding man/DisaggregationConfiguation.Rd  because i'm getting an error in this downstream branches now upon trying to Document the package 

```
Writing NAMESPACE
Error: 'DisaggregationConfiguration' is not an exported object from 'namespace:useeior'
Execution halted

Exited with status 1.
````
and i see this file should be in the man folder, which i suspect is causing the problem, and i haven't figured a way around it

**Comment by MoLi7** [comment]
I received the same error when Documenting MasterCrosswalk2012. I think it's because `DisaggregationConfiguration` is not saved as an objected yet. @jvendries and I had this [discussion](https://github.com/USEPA/useeior/commit/0f1366066b2a78d30b072b613a5a51a12899a612#diff-da5aa9b8c97edd097cf9241af669d166bfbd4faecea38531025f4bb53a1021dcR87), I'm hoping he could create a DisaggregationConfiguration.rda as well as PredefinedSectorsConfiguration.rda to meet Documentation needs.

**Comment by bl-young** [comment]
@MoLi7 @WesIngwersen  fixing this on v2-alpha now

**Pull request merged**
