### PR TITLE
Modify model name according to new naming rule

### PR DESCRIPTION
**Pull request by MoLi7**
Names of all built-in model are modified to adapt to the updated [USEEIO Model Versioning Scheme](https://github.com/USEPA/USEEIO/blob/master/VersioningScheme.md).

### CODE REVIEW

**Comment by bl-young** [comment]
@MoLi7 I think you will need to update the github actions is the model names change:
https://github.com/USEPA/useeior/blob/revisemodelname/.github/workflows/R-CMD-check.yaml#L69-L107

**Comment by WesIngwersen** [comment]
@MoLi7 @bl-young @catherinebirney @jvendries 

Beyond the scope of this PR, I think we also need a model registry. The registry would list all named models and their status.

**Comment by WesIngwersen** [comment]
One of my biggest concerns right now is the change of using this for the upcoming state EEIO models.
The state EEIO models will both use a different IO table source and will have to use different flowbysector input files. So by the rule #1, this would imply that they will have to use a different model minor version than the national models.

**Comment by MoLi7** [comment]
Did I erase a comment from you, @WesIngwersen ? I was trying to link to [rule #1](https://github.com/USEPA/USEEIO/blob/versionschemeupdate/VersioningScheme.md#rules).

**Comment by WesIngwersen** [comment]
> Did I erase a comment from you, @WesIngwersen ? I was trying to link to [rule #1](https://github.com/USEPA/USEEIO/blob/versionschemeupdate/VersioningScheme.md#rules).

No I moved it to the USEEIO PR where it was supposed to go - posted it in this PR by accident

**Comment by WesIngwersen** [comment]
This should be ready

**Comment by WesIngwersen** [comment]
useeior v1 can point to this hash for the versioning scheme used
https://github.com/USEPA/USEEIO/blob/8a43f7f5f847fe1ca6dadca3c433bceb3f29981b/VersioningScheme.md

**Comment by MoLi7** [comment]
@WesIngwersen adding space between "USEEIO" and "v" in model name makes model config file name non-portable:
https://github.com/USEPA/useeior/runs/4660555200?check_suite_focus=true#step:6:49
I think it's safer to not having space in model name.

**Comment by WesIngwersen** [comment]
We need the space just for  presentation/printing purposes.  in code its fine for now if there is no space

**Pull request merged**
