### PR TITLE
for v1.2 release

### PR DESCRIPTION
**Pull request by WesIngwersen**

### CODE REVIEW

**Comment by bl-young** [comment]
looks like `Sector_Use_2021_PRO_BeforeRedef` is still undocumented

**Comment by WesIngwersen** [comment]
> looks like `Sector_Use_2021_PRO_BeforeRedef` is still undocumented
i can address that

**Comment by WesIngwersen** [comment]
For the records the effect of the BEA data update on the draft v1.2 supply-chain-factors is notable. 
The changes are just 1% on average but are up to -32% for petro refinery products, -28% for crude oil/nat gas  and 20% for fruit crops, and 60% for dental labs. These are in reference to factors in USD 2019.

**Review by bl-young — APPROVED** [review]

**Comment by WesIngwersen** [comment]
> You use detail level models for the supply chain factors? Is this just a function of the CPI changing in these recent years?
Yes, detailed. CPI and GO changes I believe.

**Pull request merged**
