### PR TITLE
Re-organize model matrices in model$Matrices

### PR DESCRIPTION
**Pull request by MoLi7**
I thought we could simply dump all matrices into a new object `model$Matrices` then remove the original `model$A` to avoid duplicates. It's basically the same to `pointr::ptr("model$Matrices", "model[matrices]")`. Let me know what you think @WesIngwersen 

I also added `V`, `U` and `U_d` in `model$Matrices`, so they are immediately available for writing to files.

### CODE REVIEW

**Comment by WesIngwersen** [comment]
That is an option but it will require significant code changes both in useeior and in analytical code using the matrices

**Comment by MoLi7** [comment]
Let us take a step back, if we don't want `model$A` and replace it with `model$Matrices$A`, any downstream usage of `model$A` will have to be changed, because any calling of `model$A` will require the existence of `model$A`, even in the scenario of having it as a pointer to refer to the actual `model$Matrices$A`.

In fact, `pointr::ptr` cannot make `model$A` a pointer:
> pointr::ptr("model$A", "model$Matrices$A")
Error in .model$A <- function(arg = NULL) { : object of type 'closure' is not subsettable

And I don't think we can accept passing `model` as the 1st parameter in `pointr::ptr` just to avoid changes in useeior and analytical code, because it will overwrite everything in `model`.

**Comment by MoLi7** [comment]
Taking a second step back, I want to re-evaluate the cost-benefit of having `model$Matrices$A` instead of `model$A`.

I can think of two major reasons for this re-org:
1. `model` will have fewer objects and matrices are grouped - things seem tidier
2. Writing matrices will be one-step easier - no need to specify what matrices to write

But if the minimal cost of it still requires significant code changes, I'd rather we keep `model$A`, which won't necessarily make objects in `model` untidy. Then we can specify the vector of matrices upfront or in a generalized `writeModelMatrices` function in WriteModel.R.

**Comment by WesIngwersen** [comment]
Ok thats good

**Comment by WesIngwersen** [comment]
The onky reason not to specify it in WriteModel would be if differwnt models have different collections of matrices. But i dont think that is the case now

**Comment by MoLi7** [comment]
If you are thinking about MRIO models, state USEEIO models should have the same collection of matrices with USEEIOv2.

I will keep working on matrices related refactoring in this branch.

**Review by WesIngwersen — APPROVED** [review]

**Pull request merged**
