### PR TITLE
Refactor indicator handling; fix  issue #39

### PR DESCRIPTION
**Pull request by WesIngwersen**
Early commits are to fix issue #39 and add more standardization to import and saving of BEA names

The other commits revise the indicator handling in loadIndicators and in buildEEIOModel. Now Indicators is a list with a meta df and a factors df.  Factors df is now much smaller without all the baggage of all the indicator metadata fields.  

The row names of C have changed in the end to use the name and not abbreviation of the indicator as that is the field shared that links the meta and factors.

### CODE REVIEW

**Comment by WesIngwersen** [comment]
@bl-young Should work now.. I just wrote this one to compare the flow totals so across all sectors since that would be needed for models with different sector lists

**Comment by WesIngwersen** [comment]
@MoLi7 this latest commit makes sure the names are the same in the factors and meta dfs of model$Indicators

**Comment by MoLi7** [comment]
@WesIngwersen I added a few changes following our earlier discussion. Your latest commit worked well. Thanks!

**Comment by WesIngwersen** [comment]
@MoLi7 @bl-young I never got the approvals from you but i have gotten to where I'm changing a lot of non indicator related code and need to merge this and work from there

**Pull request merged**
